---
- name: Ensure that unattended-upgrades is installed and up to date
  apt:
    name: unattended-upgrades
    state: latest
  when: not unattended_upgrades_debug

- name: Ensure unattended-upgrades configuration directory
  file:
    path: "{{ unattended_upgrades_conf_directory }}"
    state: directory
    owner: "{{ unattended_upgrades_conf_directory_owner }}"
    group: "{{ unattended_upgrades_conf_directory_group }}"
    mode: '0755'

- name: Populate custom unattended-upgrades configuration
  template:
    src: 50unattended-upgrades.j2
    dest: "{{ unattended_upgrades_conf_directory }}/50unattended-upgrades"
    owner: "{{ unattended_upgrades_conf_directory_owner }}"
    group: "{{ unattended_upgrades_conf_directory_group }}"
    mode: '0644'

- name: Populate APT periodic configuration
  template:
    src: 20auto-ugprades.j2
    dest: "{{ unattended_upgrades_conf_directory }}/20auto-ugprades"
    owner: "{{ unattended_upgrades_conf_directory_owner }}"
    group: "{{ unattended_upgrades_conf_directory_group }}"
    mode: '0644'

- name: Restart unattended-upgrades service to consume updated configuration
  service:
    name: unattended-upgrades
    state: restarted
  when: not unattended_upgrades_debug
